source :gemcutter

#gem 'rails',             '2.3.2'
#gem 'rails',             '2.3.5'
gem 'rails',             '2.3.8'
gem 'rack',              '1.1.0'
gem 'haml',              '3.0.13'
gem 'simple-navigation', '>=2.7.0'
